{{ $val := .Values.services.api -}}
{{ $globals := .Values.global -}}
{{ $datastores := .Values.datastores -}}
{{ $proxy := .Values.cloudSqlAuthProxy -}}
{{ $chartVersion := .Chart.AppVersion -}}
{{- $fullName := include "secoda.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secoda.fullnameApi" . }}
  annotations: 
    {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    {{- include "secoda.labelsApi" . | nindent 4 }}selectorLabels
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "secoda.selectorLabelsApi" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secoda.selectorLabelsApi" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: secoda-dockerhub
      serviceAccountName: {{ include "secoda.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-secoda
          image: alpine:3.20
          command: ['sh', '-c', 'apk --update add curl jq && until curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -X GET https://${KUBERNETES_SERVICE_HOST}/api/v1/namespaces/secoda/configmaps | jq .items[].data | [ $(grep -c -e "secoda-opensearch-host" -e "secoda-rds-host" -e "secoda-redis-host" -e "secoda-s3-bucket") -eq 4 ]; do sleep 30; echo "30s poll for service availability"; done']
      containers:
        - name: api
          {{- with (merge $globals.securityContext $val.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ coalesce $val.image.registry $globals.image.registry }}/{{ coalesce $val.image.name $globals.image.name }}:{{ coalesce $val.image.tag $globals.image.tag $chartVersion }}"
          imagePullPolicy: {{ coalesce $val.image.pullPolicy $globals.image.pullPolicy }}
          {{- with $val.command }}
          command: {{ . }}
          {{ end }}
          {{- with  coalesce $val.args }}
          args: {{ . }}
          {{ end }}
          env: 
          {{- with (compact (concat $globals.env $val.env)) }}
             {{- toYaml . | nindent 10 }}
          {{ end }}
          - name: AUTHORIZED_DOMAINS
            value:  {{ $datastores.secoda.authorized_domains }}
          - name: REDIS_EC_HOST
            valueFrom:
              configMapKeyRef:
                name: "{{ $fullName }}-redis-conn-cm"
                key: "{{ .Release.Namespace }}.{{ $fullName }}-redis-host"
          - name: REDIS_EC_PORT
            valueFrom:
              configMapKeyRef:
                name: "{{ $fullName }}-redis-conn-cm"
                key: "{{ .Release.Namespace }}.{{ $fullName }}-redis-port"
          - name: REDIS_URL
            value: "redis://$(REDIS_EC_HOST):$(REDIS_EC_PORT)"
          - name: ES_HOST
            valueFrom:
              configMapKeyRef:
                name: "{{ $fullName }}-opensearch-conn-cm"
                key: "{{ .Release.Namespace }}.{{ $fullName }}-opensearch-host"
          - name: ES_USERNAME
            value: elastic
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "secoda-keycloak-password"
                key: ES_PASSWORD
          - name: VITE_NEW_AUTH
            value: "true"
          - name: DB_RDS_HOST
            valueFrom:
              configMapKeyRef:
                name: "{{ $fullName }}-rds-conn-cm"
                key: "{{ .Release.Namespace }}.{{ $fullName }}-rds-host"
          - name: DB_RDS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "secoda-keycloak-password"
                key: DB_PASSWORD
          - name: APISERVICE_DATABASE_CONNECTION
            value: "postgresql://keycloak:$(DB_RDS_PASSWORD)@$(DB_RDS_HOST):5432/secoda"
          - name: APISERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "secoda-keycloak-password"
                key: APISERVICE_SECRET
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: "secoda-keycloak-password"
                key: PUBLIC_KEY
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: "secoda-keycloak-password"
                key: PRIVATE_KEY
          {{- with $val.ports }}
          ports: 
           {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $val.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $val.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $val.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $val.resources | nindent 12 }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelectorApi }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
