{{ $val := .Values.serviceAccount -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secoda.serviceAccountName" . }}
  namespace: {{ $val.namespace }}
  labels:
    {{- include "secoda.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $val.role_arn }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
  namespace: {{ $val.namespace }}
rules:
  - apiGroups:
        - ""
    resources:
      - configmaps
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
subjects:
- namespace: {{ $val.namespace }}
  kind: ServiceAccount
  name: {{ include "secoda.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role
{{- end }}
